site_name: pychebfun
repo_url: https://github.com/pychebfun/pychebfun
site_url: https://pychebfun.github.io/pychebfun
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Olivier Verdier
edit_uri: edit/main/docs/
repo_name: pychebfun/pychebfun
copyright: Maintained by <a href="https://olivierverdier.com">olivierverdier</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/pychebfun"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pychebfun/pychebfun
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pychebfun

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
